version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: DockerFile-node
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    build:
      context: .
      dockerfile: DockerFile-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: