name : streaming_ms
version: '3.8'
services:
  nestjs-app:
    build:
      context: .
      dockerfile: DockerFile-node
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    depends_on:
      - mongodb-docker
    networks:
      - sound-streamings
    links:
      - mongodb-docker:mongodb-docker

  mongodb-docker:
    build:
      context: .
      dockerfile: DockerFile-mongodb
    restart: always
    ports:
      - "27019:27017"
    networks:
      - sound-streamings

volumes:
  mongodb-data:

networks:
  sound-streamings: 
    driver: bridge 
  